import { Business, Customer, Invoice, Payment, Expense, Sale } from '../../src/types.js';

export function getSyntheticDemoData(): {
  business: Business;
  customers: Customer[];
  invoices: Invoice[];
  payments: Payment[];
  expenses: Expense[];
  sales: Sale[];
} {
  const business: Business = {
    id: 'biz_precision_001',
    name: 'Precision Tooling & Components Pvt. Ltd.',
    industry: 'Precision Auto & Industrial Engineering',
    currency: 'INR',
    currencySymbol: '₹',
    currentCash: 540000, // ₹5.4 Lakhs
    minimumCashReserve: 300000, // ₹3.0 Lakhs minimum safety buffer
    createdAt: '2026-01-01',
    isDemo: true,
  };

  const customers: Customer[] = [
    {
      id: 'cust_apex_01',
      businessId: business.id,
      name: 'Apex Motors Ltd.',
      totalRevenue: 2450000,
      invoiceCount: 8,
      outstandingAmount: 380000,
      averagePaymentDelay: 22,
      medianPaymentDelay: 20,
      paymentReliability: 'LOW',
      revenueShare: 44.5,
      contactPerson: 'Mr. R. Sharma (Head of Procurement)',
      email: 'r.sharma@apexmotors.demo',
    },
    {
      id: 'cust_kavita_02',
      businessId: business.id,
      name: 'Kavita Industrial Equipments',
      totalRevenue: 1150000,
      invoiceCount: 6,
      outstandingAmount: 125000,
      averagePaymentDelay: 5,
      medianPaymentDelay: 4,
      paymentReliability: 'HIGH',
      revenueShare: 20.9,
      contactPerson: 'S. Kulkarni',
      email: 'procurement@kavitaindustries.demo',
    },
    {
      id: 'cust_bharat_03',
      businessId: business.id,
      name: 'Bharat Agro Engineering',
      totalRevenue: 850000,
      invoiceCount: 5,
      outstandingAmount: 95000,
      averagePaymentDelay: 12,
      medianPaymentDelay: 10,
      paymentReliability: 'MEDIUM',
      revenueShare: 15.5,
      contactPerson: 'V. Patel',
      email: 'accounts@bharatagro.demo',
    },
    {
      id: 'cust_zenith_04',
      businessId: business.id,
      name: 'Zenith Precision Assemblies',
      totalRevenue: 560000,
      invoiceCount: 4,
      outstandingAmount: 45000,
      averagePaymentDelay: -2, // Pays 2 days before due date
      medianPaymentDelay: -1,
      paymentReliability: 'HIGH',
      revenueShare: 10.2,
      contactPerson: 'Ananya Roy',
      email: 'aroy@zenithprecision.demo',
    },
    {
      id: 'cust_southern_05',
      businessId: business.id,
      name: 'Southern Pumps & Valves',
      totalRevenue: 320000,
      invoiceCount: 3,
      outstandingAmount: 68000,
      averagePaymentDelay: 26,
      medianPaymentDelay: 25,
      paymentReliability: 'LOW',
      revenueShare: 5.8,
      contactPerson: 'K. Nair',
      email: 'knair@southernpumps.demo',
    },
    {
      id: 'cust_metro_06',
      businessId: business.id,
      name: 'Metro ElectroTech Systems',
      totalRevenue: 170000,
      invoiceCount: 2,
      outstandingAmount: 20000,
      averagePaymentDelay: 2,
      medianPaymentDelay: 2,
      paymentReliability: 'HIGH',
      revenueShare: 3.1,
      contactPerson: 'D. Banerjee',
      email: 'dbanerjee@metroelectrotech.demo',
    },
  ];

  // Invoices over 6 months with realistic numbers and dates relative to 2026-09-14
  const invoices: Invoice[] = [
    // Current / Outstanding / Overdue Invoices
    {
      id: 'inv_2026_101',
      businessId: business.id,
      customerId: 'cust_apex_01',
      customerName: 'Apex Motors Ltd.',
      invoiceNumber: 'INV-2026-089',
      issueDate: '2026-07-15',
      dueDate: '2026-08-15', // 30 days overdue
      amount: 220000,
      taxAmount: 39600,
      outstandingAmount: 220000,
      status: 'OVERDUE',
      extractionConfidence: 0.98,
      daysOverdue: 30,
      lineItems: [
        { description: 'CNC Turned Flange Assemblies - Batch A', quantity: 200, unitPrice: 850, amount: 170000 },
        { description: 'Surface Hardening & QA Certification', quantity: 200, unitPrice: 250, amount: 50000 },
      ],
    },
    {
      id: 'inv_2026_102',
      businessId: business.id,
      customerId: 'cust_apex_01',
      customerName: 'Apex Motors Ltd.',
      invoiceNumber: 'INV-2026-095',
      issueDate: '2026-08-10',
      dueDate: '2026-09-10', // 4 days overdue
      amount: 160000,
      taxAmount: 28800,
      outstandingAmount: 160000,
      status: 'OVERDUE',
      extractionConfidence: 0.96,
      daysOverdue: 4,
      lineItems: [
        { description: 'Forged Shaft Pinions', quantity: 100, unitPrice: 1600, amount: 160000 },
      ],
    },
    {
      id: 'inv_2026_103',
      businessId: business.id,
      customerId: 'cust_kavita_02',
      customerName: 'Kavita Industrial Equipments',
      invoiceNumber: 'INV-2026-099',
      issueDate: '2026-08-25',
      dueDate: '2026-09-25', // Due in 11 days (Current)
      amount: 125000,
      taxAmount: 22500,
      outstandingAmount: 125000,
      status: 'UNPAID',
      extractionConfidence: 0.99,
      daysOverdue: 0,
      lineItems: [
        { description: 'High Tensile Studs & Couplings', quantity: 500, unitPrice: 250, amount: 125000 },
      ],
    },
    {
      id: 'inv_2026_104',
      businessId: business.id,
      customerId: 'cust_bharat_03',
      customerName: 'Bharat Agro Engineering',
      invoiceNumber: 'INV-2026-092',
      issueDate: '2026-08-01',
      dueDate: '2026-08-31', // 14 days overdue
      amount: 95000,
      taxAmount: 17100,
      outstandingAmount: 95000,
      status: 'OVERDUE',
      extractionConfidence: 0.95,
      daysOverdue: 14,
      lineItems: [
        { description: 'Cast Iron Harvester Bushings', quantity: 150, unitPrice: 633.33, amount: 95000 },
      ],
    },
    {
      id: 'inv_2026_105',
      businessId: business.id,
      customerId: 'cust_zenith_04',
      customerName: 'Zenith Precision Assemblies',
      invoiceNumber: 'INV-2026-102',
      issueDate: '2026-09-02',
      dueDate: '2026-10-02', // Current
      amount: 45000,
      taxAmount: 8100,
      outstandingAmount: 45000,
      status: 'UNPAID',
      extractionConfidence: 0.97,
      daysOverdue: 0,
    },
    {
      id: 'inv_2026_106',
      businessId: business.id,
      customerId: 'cust_southern_05',
      customerName: 'Southern Pumps & Valves',
      invoiceNumber: 'INV-2026-084',
      issueDate: '2026-06-28',
      dueDate: '2026-07-28', // 48 days overdue
      amount: 68000,
      taxAmount: 12240,
      outstandingAmount: 68000,
      status: 'OVERDUE',
      extractionConfidence: 0.94,
      daysOverdue: 48,
    },
    {
      id: 'inv_2026_107',
      businessId: business.id,
      customerId: 'cust_metro_06',
      customerName: 'Metro ElectroTech Systems',
      invoiceNumber: 'INV-2026-103',
      issueDate: '2026-09-05',
      dueDate: '2026-09-20', // Due in 6 days
      amount: 20000,
      taxAmount: 3600,
      outstandingAmount: 20000,
      status: 'UNPAID',
      extractionConfidence: 0.99,
      daysOverdue: 0,
    },

    // Settled Historical Invoices (Demonstrating payment delay patterns)
    {
      id: 'inv_hist_01',
      businessId: business.id,
      customerId: 'cust_apex_01',
      customerName: 'Apex Motors Ltd.',
      invoiceNumber: 'INV-2026-042',
      issueDate: '2026-03-10',
      dueDate: '2026-04-10',
      amount: 340000,
      outstandingAmount: 0,
      status: 'PAID',
      extractionConfidence: 0.99,
      daysOverdue: 0,
    },
    {
      id: 'inv_hist_02',
      businessId: business.id,
      customerId: 'cust_apex_01',
      customerName: 'Apex Motors Ltd.',
      invoiceNumber: 'INV-2026-056',
      issueDate: '2026-04-15',
      dueDate: '2026-05-15',
      amount: 410000,
      outstandingAmount: 0,
      status: 'PAID',
      extractionConfidence: 0.98,
      daysOverdue: 0,
    },
    {
      id: 'inv_hist_03',
      businessId: business.id,
      customerId: 'cust_apex_01',
      customerName: 'Apex Motors Ltd.',
      invoiceNumber: 'INV-2026-068',
      issueDate: '2026-05-20',
      dueDate: '2026-06-20',
      amount: 480000,
      outstandingAmount: 0,
      status: 'PAID',
      extractionConfidence: 0.97,
      daysOverdue: 0,
    },
    {
      id: 'inv_hist_04',
      businessId: business.id,
      customerId: 'cust_apex_01',
      customerName: 'Apex Motors Ltd.',
      invoiceNumber: 'INV-2026-079',
      issueDate: '2026-06-18',
      dueDate: '2026-07-18',
      amount: 440000,
      outstandingAmount: 0,
      status: 'PAID',
      extractionConfidence: 0.99,
      daysOverdue: 0,
    },
    {
      id: 'inv_hist_05',
      businessId: business.id,
      customerId: 'cust_apex_01',
      customerName: 'Apex Motors Ltd.',
      invoiceNumber: 'INV-2026-081',
      issueDate: '2026-07-02',
      dueDate: '2026-08-02',
      amount: 400000,
      outstandingAmount: 0,
      status: 'PAID',
      extractionConfidence: 0.96,
      daysOverdue: 0,
    },
    // Kavita historical
    {
      id: 'inv_hist_06',
      businessId: business.id,
      customerId: 'cust_kavita_02',
      customerName: 'Kavita Industrial Equipments',
      invoiceNumber: 'INV-2026-045',
      issueDate: '2026-03-25',
      dueDate: '2026-04-25',
      amount: 240000,
      outstandingAmount: 0,
      status: 'PAID',
      extractionConfidence: 0.98,
      daysOverdue: 0,
    },
    {
      id: 'inv_hist_07',
      businessId: business.id,
      customerId: 'cust_kavita_02',
      customerName: 'Kavita Industrial Equipments',
      invoiceNumber: 'INV-2026-061',
      issueDate: '2026-05-05',
      dueDate: '2026-06-05',
      amount: 280000,
      outstandingAmount: 0,
      status: 'PAID',
      extractionConfidence: 0.99,
      daysOverdue: 0,
    },
    {
      id: 'inv_hist_08',
      businessId: business.id,
      customerId: 'cust_kavita_02',
      customerName: 'Kavita Industrial Equipments',
      invoiceNumber: 'INV-2026-075',
      issueDate: '2026-06-20',
      dueDate: '2026-07-20',
      amount: 275000,
      outstandingAmount: 0,
      status: 'PAID',
      extractionConfidence: 0.97,
      daysOverdue: 0,
    },
    {
      id: 'inv_hist_09',
      businessId: business.id,
      customerId: 'cust_kavita_02',
      customerName: 'Kavita Industrial Equipments',
      invoiceNumber: 'INV-2026-085',
      issueDate: '2026-07-18',
      dueDate: '2026-08-18',
      amount: 230000,
      outstandingAmount: 0,
      status: 'PAID',
      extractionConfidence: 0.99,
      daysOverdue: 0,
    },
    // Bharat historical
    {
      id: 'inv_hist_10',
      businessId: business.id,
      customerId: 'cust_bharat_03',
      customerName: 'Bharat Agro Engineering',
      invoiceNumber: 'INV-2026-048',
      issueDate: '2026-04-02',
      dueDate: '2026-05-02',
      amount: 190000,
      outstandingAmount: 0,
      status: 'PAID',
      extractionConfidence: 0.95,
      daysOverdue: 0,
    },
    {
      id: 'inv_hist_11',
      businessId: business.id,
      customerId: 'cust_bharat_03',
      customerName: 'Bharat Agro Engineering',
      invoiceNumber: 'INV-2026-065',
      issueDate: '2026-05-18',
      dueDate: '2026-06-18',
      amount: 260000,
      outstandingAmount: 0,
      status: 'PAID',
      extractionConfidence: 0.96,
      daysOverdue: 0,
    },
    {
      id: 'inv_hist_12',
      businessId: business.id,
      customerId: 'cust_bharat_03',
      customerName: 'Bharat Agro Engineering',
      invoiceNumber: 'INV-2026-078',
      issueDate: '2026-06-25',
      dueDate: '2026-07-25',
      amount: 305000,
      outstandingAmount: 0,
      status: 'PAID',
      extractionConfidence: 0.98,
      daysOverdue: 0,
    },
    // Zenith historical
    {
      id: 'inv_hist_13',
      businessId: business.id,
      customerId: 'cust_zenith_04',
      customerName: 'Zenith Precision Assemblies',
      invoiceNumber: 'INV-2026-052',
      issueDate: '2026-04-10',
      dueDate: '2026-05-10',
      amount: 170000,
      outstandingAmount: 0,
      status: 'PAID',
      extractionConfidence: 0.99,
      daysOverdue: 0,
    },
    {
      id: 'inv_hist_14',
      businessId: business.id,
      customerId: 'cust_zenith_04',
      customerName: 'Zenith Precision Assemblies',
      invoiceNumber: 'INV-2026-072',
      issueDate: '2026-06-08',
      dueDate: '2026-07-08',
      amount: 195000,
      outstandingAmount: 0,
      status: 'PAID',
      extractionConfidence: 0.98,
      daysOverdue: 0,
    },
    {
      id: 'inv_hist_15',
      businessId: business.id,
      customerId: 'cust_zenith_04',
      customerName: 'Zenith Precision Assemblies',
      invoiceNumber: 'INV-2026-088',
      issueDate: '2026-07-22',
      dueDate: '2026-08-22',
      amount: 150000,
      outstandingAmount: 0,
      status: 'PAID',
      extractionConfidence: 0.97,
      daysOverdue: 0,
    },
    // Southern historical
    {
      id: 'inv_hist_16',
      businessId: business.id,
      customerId: 'cust_southern_05',
      customerName: 'Southern Pumps & Valves',
      invoiceNumber: 'INV-2026-058',
      issueDate: '2026-04-20',
      dueDate: '2026-05-20',
      amount: 110000,
      outstandingAmount: 0,
      status: 'PAID',
      extractionConfidence: 0.94,
      daysOverdue: 0,
    },
    {
      id: 'inv_hist_17',
      businessId: business.id,
      customerId: 'cust_southern_05',
      customerName: 'Southern Pumps & Valves',
      invoiceNumber: 'INV-2026-070',
      issueDate: '2026-05-28',
      dueDate: '2026-06-28',
      amount: 142000,
      outstandingAmount: 0,
      status: 'PAID',
      extractionConfidence: 0.95,
      daysOverdue: 0,
    },
    // Metro historical
    {
      id: 'inv_hist_18',
      businessId: business.id,
      customerId: 'cust_metro_06',
      customerName: 'Metro ElectroTech Systems',
      invoiceNumber: 'INV-2026-066',
      issueDate: '2026-05-15',
      dueDate: '2026-06-05',
      amount: 150000,
      outstandingAmount: 0,
      status: 'PAID',
      extractionConfidence: 0.99,
      daysOverdue: 0,
    },
  ];

  // Payments matching invoices, showing realistic delays
  const payments: Payment[] = [
    {
      id: 'pay_01',
      businessId: business.id,
      customerId: 'cust_apex_01',
      customerName: 'Apex Motors Ltd.',
      invoiceId: 'inv_hist_01',
      invoiceNumber: 'INV-2026-042',
      amount: 340000,
      paymentDate: '2026-05-02', // 22 days late
      reference: 'NEFT-APEX-9482910',
      paymentType: 'BANK_TRANSFER',
      description: 'NEFT Inward APEX MOTORS LTD INV 042',
      reconciliationConfidence: 0.99,
      reconciliationStatus: 'MATCHED',
    },
    {
      id: 'pay_02',
      businessId: business.id,
      customerId: 'cust_apex_01',
      customerName: 'Apex Motors Ltd.',
      invoiceId: 'inv_hist_02',
      invoiceNumber: 'INV-2026-056',
      amount: 410000,
      paymentDate: '2026-06-09', // 25 days late
      reference: 'RTGS-APEX-1184920',
      paymentType: 'BANK_TRANSFER',
      description: 'RTGS Inward APEX MOTORS LTD INV 056',
      reconciliationConfidence: 0.99,
      reconciliationStatus: 'MATCHED',
    },
    {
      id: 'pay_03',
      businessId: business.id,
      customerId: 'cust_apex_01',
      customerName: 'Apex Motors Ltd.',
      invoiceId: 'inv_hist_03',
      invoiceNumber: 'INV-2026-068',
      amount: 480000,
      paymentDate: '2026-07-12', // 22 days late
      reference: 'RTGS-APEX-3392019',
      paymentType: 'BANK_TRANSFER',
      description: 'RTGS Inward APEX MOTORS INV 068',
      reconciliationConfidence: 0.99,
      reconciliationStatus: 'MATCHED',
    },
    {
      id: 'pay_04',
      businessId: business.id,
      customerId: 'cust_apex_01',
      customerName: 'Apex Motors Ltd.',
      invoiceId: 'inv_hist_04',
      invoiceNumber: 'INV-2026-079',
      amount: 440000,
      paymentDate: '2026-08-08', // 21 days late
      reference: 'RTGS-APEX-7749102',
      paymentType: 'BANK_TRANSFER',
      description: 'RTGS APEX MOTORS PVT INV 079',
      reconciliationConfidence: 0.98,
      reconciliationStatus: 'MATCHED',
    },
    {
      id: 'pay_05',
      businessId: business.id,
      customerId: 'cust_apex_01',
      customerName: 'Apex Motors Ltd.',
      invoiceId: 'inv_hist_05',
      invoiceNumber: 'INV-2026-081',
      amount: 400000,
      paymentDate: '2026-08-24', // 22 days late
      reference: 'RTGS-APEX-8830192',
      paymentType: 'BANK_TRANSFER',
      description: 'RTGS APEX MOTORS INV 081',
      reconciliationConfidence: 0.99,
      reconciliationStatus: 'MATCHED',
    },
    // Kavita payments (reliable)
    {
      id: 'pay_06',
      businessId: business.id,
      customerId: 'cust_kavita_02',
      customerName: 'Kavita Industrial Equipments',
      invoiceId: 'inv_hist_06',
      invoiceNumber: 'INV-2026-045',
      amount: 240000,
      paymentDate: '2026-04-30', // 5 days late
      reference: 'CMS-KAV-492011',
      paymentType: 'BANK_TRANSFER',
      reconciliationConfidence: 0.99,
      reconciliationStatus: 'MATCHED',
    },
    {
      id: 'pay_07',
      businessId: business.id,
      customerId: 'cust_kavita_02',
      customerName: 'Kavita Industrial Equipments',
      invoiceId: 'inv_hist_07',
      invoiceNumber: 'INV-2026-061',
      amount: 280000,
      paymentDate: '2026-06-09', // 4 days late
      reference: 'CMS-KAV-582039',
      paymentType: 'BANK_TRANSFER',
      reconciliationConfidence: 0.99,
      reconciliationStatus: 'MATCHED',
    },
    {
      id: 'pay_08',
      businessId: business.id,
      customerId: 'cust_kavita_02',
      customerName: 'Kavita Industrial Equipments',
      invoiceId: 'inv_hist_08',
      invoiceNumber: 'INV-2026-075',
      amount: 275000,
      paymentDate: '2026-07-24', // 4 days late
      reference: 'CMS-KAV-829103',
      paymentType: 'BANK_TRANSFER',
      reconciliationConfidence: 0.99,
      reconciliationStatus: 'MATCHED',
    },
    {
      id: 'pay_09',
      businessId: business.id,
      customerId: 'cust_kavita_02',
      customerName: 'Kavita Industrial Equipments',
      invoiceId: 'inv_hist_09',
      invoiceNumber: 'INV-2026-085',
      amount: 230000,
      paymentDate: '2026-08-25', // 7 days late
      reference: 'CMS-KAV-991024',
      paymentType: 'BANK_TRANSFER',
      reconciliationConfidence: 0.99,
      reconciliationStatus: 'MATCHED',
    },
    // Bharat Agro payments
    {
      id: 'pay_10',
      businessId: business.id,
      customerId: 'cust_bharat_03',
      customerName: 'Bharat Agro Engineering',
      invoiceId: 'inv_hist_10',
      invoiceNumber: 'INV-2026-048',
      amount: 190000,
      paymentDate: '2026-05-14', // 12 days late
      reference: 'NEFT-BHARAT-39102',
      paymentType: 'BANK_TRANSFER',
      reconciliationConfidence: 0.97,
      reconciliationStatus: 'MATCHED',
    },
    {
      id: 'pay_11',
      businessId: business.id,
      customerId: 'cust_bharat_03',
      customerName: 'Bharat Agro Engineering',
      invoiceId: 'inv_hist_11',
      invoiceNumber: 'INV-2026-065',
      amount: 260000,
      paymentDate: '2026-06-30', // 12 days late
      reference: 'NEFT-BHARAT-74910',
      paymentType: 'BANK_TRANSFER',
      reconciliationConfidence: 0.98,
      reconciliationStatus: 'MATCHED',
    },
    {
      id: 'pay_12',
      businessId: business.id,
      customerId: 'cust_bharat_03',
      customerName: 'Bharat Agro Engineering',
      invoiceId: 'inv_hist_12',
      invoiceNumber: 'INV-2026-078',
      amount: 305000,
      paymentDate: '2026-08-07', // 13 days late
      reference: 'NEFT-BHARAT-91024',
      paymentType: 'BANK_TRANSFER',
      reconciliationConfidence: 0.97,
      reconciliationStatus: 'MATCHED',
    },
    // Zenith payments (prompt / early)
    {
      id: 'pay_13',
      businessId: business.id,
      customerId: 'cust_zenith_04',
      customerName: 'Zenith Precision Assemblies',
      invoiceId: 'inv_hist_13',
      invoiceNumber: 'INV-2026-052',
      amount: 170000,
      paymentDate: '2026-05-08', // 2 days early
      reference: 'UPI-ZENITH-49201',
      paymentType: 'UPI',
      reconciliationConfidence: 0.99,
      reconciliationStatus: 'MATCHED',
    },
    {
      id: 'pay_14',
      businessId: business.id,
      customerId: 'cust_zenith_04',
      customerName: 'Zenith Precision Assemblies',
      invoiceId: 'inv_hist_14',
      invoiceNumber: 'INV-2026-072',
      amount: 195000,
      paymentDate: '2026-07-06', // 2 days early
      reference: 'UPI-ZENITH-88391',
      paymentType: 'UPI',
      reconciliationConfidence: 0.99,
      reconciliationStatus: 'MATCHED',
    },
    {
      id: 'pay_15',
      businessId: business.id,
      customerId: 'cust_zenith_04',
      customerName: 'Zenith Precision Assemblies',
      invoiceId: 'inv_hist_15',
      invoiceNumber: 'INV-2026-088',
      amount: 150000,
      paymentDate: '2026-08-20', // 2 days early
      reference: 'UPI-ZENITH-99201',
      paymentType: 'UPI',
      reconciliationConfidence: 0.99,
      reconciliationStatus: 'MATCHED',
    },
    // Southern payments (very late)
    {
      id: 'pay_16',
      businessId: business.id,
      customerId: 'cust_southern_05',
      customerName: 'Southern Pumps & Valves',
      invoiceId: 'inv_hist_16',
      invoiceNumber: 'INV-2026-058',
      amount: 110000,
      paymentDate: '2026-06-15', // 26 days late
      reference: 'CHQ-SOUTHERN-01924',
      paymentType: 'CHEQUE',
      reconciliationConfidence: 0.95,
      reconciliationStatus: 'MATCHED',
    },
    {
      id: 'pay_17',
      businessId: business.id,
      customerId: 'cust_southern_05',
      customerName: 'Southern Pumps & Valves',
      invoiceId: 'inv_hist_17',
      invoiceNumber: 'INV-2026-070',
      amount: 142000,
      paymentDate: '2026-07-24', // 26 days late
      reference: 'CHQ-SOUTHERN-02294',
      paymentType: 'CHEQUE',
      reconciliationConfidence: 0.95,
      reconciliationStatus: 'MATCHED',
    },
    // Metro payment
    {
      id: 'pay_18',
      businessId: business.id,
      customerId: 'cust_metro_06',
      customerName: 'Metro ElectroTech Systems',
      invoiceId: 'inv_hist_18',
      invoiceNumber: 'INV-2026-066',
      amount: 150000,
      paymentDate: '2026-06-07', // 2 days late
      reference: 'NEFT-METRO-449102',
      paymentType: 'BANK_TRANSFER',
      reconciliationConfidence: 0.99,
      reconciliationStatus: 'MATCHED',
    },
    // An ambiguous / partial payment for reconciliation UI demo
    {
      id: 'pay_ambiguous_01',
      businessId: business.id,
      amount: 50000,
      paymentDate: '2026-09-08',
      reference: 'UPI-INWARD-98201948',
      paymentType: 'UPI',
      description: 'UPI/P2A/CR/98201948/PRECISION PARTIAL ADVANCE',
      reconciliationConfidence: 0.65,
      reconciliationStatus: 'NEEDS_REVIEW',
      possibleMatches: [
        { invoiceId: 'inv_2026_105', invoiceNumber: 'INV-2026-102', customerName: 'Zenith Precision Assemblies', confidence: 0.68, reason: 'Amount close to ₹45,000' },
        { invoiceId: 'inv_2026_106', invoiceNumber: 'INV-2026-084', customerName: 'Southern Pumps & Valves', confidence: 0.62, reason: 'Partial payment on overdue ₹68,000' }
      ]
    }
  ];

  // Recurring and operating monthly expenses (monthly burn ~₹4.8L to ₹5.1L)
  const expenses: Expense[] = [
    // August & September 2026 expenses
    {
      id: 'exp_01',
      businessId: business.id,
      category: 'PAYROLL',
      amount: 185000,
      date: '2026-08-01',
      dueDate: '2026-08-07',
      recurring: true,
      frequency: 'MONTHLY',
      critical: true,
      description: 'Factory Operators & Tech Staff Wages (Aug)',
    },
    {
      id: 'exp_02',
      businessId: business.id,
      category: 'PAYROLL',
      amount: 185000,
      date: '2026-09-01',
      dueDate: '2026-09-07',
      recurring: true,
      frequency: 'MONTHLY',
      critical: true,
      description: 'Factory Operators & Tech Staff Wages (Sep)',
    },
    {
      id: 'exp_03',
      businessId: business.id,
      category: 'RENT',
      amount: 65000,
      date: '2026-08-05',
      dueDate: '2026-08-05',
      recurring: true,
      frequency: 'MONTHLY',
      critical: true,
      description: 'MIDC Industrial Shed Lease Rental',
    },
    {
      id: 'exp_04',
      businessId: business.id,
      category: 'RENT',
      amount: 65000,
      date: '2026-09-05',
      dueDate: '2026-09-05',
      recurring: true,
      frequency: 'MONTHLY',
      critical: true,
      description: 'MIDC Industrial Shed Lease Rental',
    },
    {
      id: 'exp_05',
      businessId: business.id,
      category: 'UTILITIES',
      amount: 48000,
      date: '2026-08-10',
      dueDate: '2026-08-15',
      recurring: true,
      frequency: 'MONTHLY',
      critical: true,
      description: 'Industrial HT Power Tariff MSEDCL',
    },
    {
      id: 'exp_06',
      businessId: business.id,
      category: 'UTILITIES',
      amount: 46000,
      date: '2026-09-10',
      dueDate: '2026-09-15',
      recurring: true,
      frequency: 'MONTHLY',
      critical: true,
      description: 'Industrial HT Power Tariff MSEDCL',
    },
    {
      id: 'exp_07',
      businessId: business.id,
      category: 'RAW_MATERIALS',
      amount: 135000,
      date: '2026-08-18',
      recurring: true,
      frequency: 'MONTHLY',
      critical: true,
      description: 'EN8 & SS316 Round Bar Consignment',
    },
    {
      id: 'exp_08',
      businessId: business.id,
      category: 'RAW_MATERIALS',
      amount: 142000,
      date: '2026-09-02',
      recurring: true,
      frequency: 'MONTHLY',
      critical: true,
      description: 'Forging Billets & Carbide Inserts',
    },
    {
      id: 'exp_09',
      businessId: business.id,
      category: 'MACHINERY_MAINTENANCE',
      amount: 28000,
      date: '2026-08-22',
      recurring: true,
      frequency: 'MONTHLY',
      critical: false,
      description: 'CNC Machine 3 & 4 Spindle Servicing',
    },
    {
      id: 'exp_10',
      businessId: business.id,
      category: 'LOGISTICS',
      amount: 22000,
      date: '2026-08-28',
      recurring: true,
      frequency: 'MONTHLY',
      critical: false,
      description: 'Heavy Trucking Dispatch to OEM Plants',
    },
    {
      id: 'exp_11',
      businessId: business.id,
      category: 'TAXES_STATUTORY',
      amount: 32000,
      date: '2026-08-20',
      dueDate: '2026-08-20',
      recurring: true,
      frequency: 'MONTHLY',
      critical: true,
      description: 'GST Monthly Return & PF/ESI Contribution',
    },
    // Upcoming scheduled expenses in next 30 days
    {
      id: 'exp_next_01',
      businessId: business.id,
      category: 'TAXES_STATUTORY',
      amount: 35000,
      date: '2026-09-20',
      dueDate: '2026-09-20',
      recurring: true,
      frequency: 'MONTHLY',
      critical: true,
      description: 'Advance Tax Q2 & GST Settlement',
    },
    {
      id: 'exp_next_02',
      businessId: business.id,
      category: 'RAW_MATERIALS',
      amount: 120000,
      date: '2026-09-25',
      dueDate: '2026-09-25',
      recurring: true,
      frequency: 'MONTHLY',
      critical: true,
      description: 'Steel Coil Shipment (Contractual Delivery)',
    },
    {
      id: 'exp_next_03',
      businessId: business.id,
      category: 'PAYROLL',
      amount: 185000,
      date: '2026-10-01',
      dueDate: '2026-10-07',
      recurring: true,
      frequency: 'MONTHLY',
      critical: true,
      description: 'Core Workforce Wages (Oct)',
    },
    {
      id: 'exp_next_04',
      businessId: business.id,
      category: 'RENT',
      amount: 65000,
      date: '2026-10-05',
      dueDate: '2026-10-05',
      recurring: true,
      frequency: 'MONTHLY',
      critical: true,
      description: 'Factory Lease (Oct)',
    },
  ];

  // Sales records
  const sales: Sale[] = invoices.map((inv) => ({
    id: `sale_${inv.id}`,
    businessId: business.id,
    customerId: inv.customerId,
    customerName: inv.customerName,
    date: inv.issueDate,
    amount: inv.amount,
    category: 'Engineered Precision Components',
  }));

  return {
    business,
    customers,
    invoices,
    payments,
    expenses,
    sales,
  };
}
