import React from 'react';
import {
  Users,
  AlertTriangle,
  CheckCircle2,
  Clock,
  Play,
  Building2,
  Percent,
  SlidersHorizontal,
} from 'lucide-react';
import { Customer, ConcentrationMetric } from '../types';
import {
  PieChart,
  Pie,
  Cell,
  Tooltip,
  ResponsiveContainer,
} from 'recharts';

interface CustomersViewProps {
  concentration: ConcentrationMetric | null;
  customers: Customer[];
  onSimulateCustomerDelay: (customer: Customer, delayDays: number) => void;
}

export const CustomersView: React.FC<CustomersViewProps> = ({
  concentration,
  customers = [],
  onSimulateCustomerDelay,
}) => {
  const COLORS = ['#7a6ab4', '#4a75a5', '#3f7b58', '#b37346', '#c4697e', '#8874aa'];

  const safeCustomers = customers || [];
  const pieData = safeCustomers.map((c) => ({
    name: c.name,
    value: c.totalRevenue,
    share: c.revenueShare,
  }));

  return (
    <div className="space-y-6 pb-12">
      {/* View Header */}
      <div className="pb-2 border-b border-[#dcd4f2]">
        <h2 className="text-xl sm:text-2xl font-extrabold text-[#212534] tracking-tight">
          Customer Concentration & Counterparty Exposure
        </h2>
        <p className="text-xs text-[#565d70] mt-0.5">
          Assess corporate buyer revenue concentration and stress-test payment delay exposure.
        </p>
      </div>

      {/* Dependency Warning Callout Banner (Soft Blush / Rose Surface) */}
      {concentration?.hasDangerousDependency && (
        <div className="neu-card-blush p-5 flex items-start gap-4">
          <div className="w-10 h-10 rounded-xl neu-inset-blush flex items-center justify-center text-[#b95d77] shrink-0">
            <AlertTriangle className="w-5 h-5" />
          </div>
          <div className="text-xs text-[#733045]">
            <h4 className="font-extrabold text-sm text-[#b95d77]">
              Counterparty Concentration Notice: {concentration.top1CustomerName}
            </h4>
            <p className="mt-1 leading-relaxed font-medium">
              Your largest client represents <strong>{concentration.top1CustomerShare}% of total turnover</strong>.
              In industrial engineering, client concentration above 30% creates elevated vulnerability. We recommend exploring invoice discounting on TReDS and securing partial upfront advances for future order runs.
            </p>
          </div>
        </div>
      )}

      {/* Concentration KPIs & Distribution Chart */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left: Summary Metrics */}
        <div className="lg:col-span-4 space-y-4">
          <div className="neu-card-lavender p-5">
            <span className="text-xs font-bold text-[#483a7a] block mb-1">
              Top Customer Revenue Share
            </span>
            <div className="flex items-baseline gap-2">
              <span className="text-3xl font-extrabold text-[#212534] tracking-tight">
                {concentration?.top1CustomerShare}%
              </span>
              <span className="text-xs font-bold text-[#7a6ab4] truncate">
                ({concentration?.top1CustomerName})
              </span>
            </div>
            <div className="mt-3 text-[11px] text-[#7a6ab4] font-medium">
              Industrial Target: &le; 30% per account
            </div>
          </div>

          <div className="neu-card-blue p-5">
            <span className="text-xs font-bold text-[#2c4d72] block mb-1">
              Top 3 Customers Combined Share
            </span>
            <div className="flex items-baseline gap-2">
              <span className="text-3xl font-extrabold text-[#4a75a5] tracking-tight">
                {concentration?.top3CustomerShare}%
              </span>
            </div>
            <div className="mt-3 text-[11px] text-[#4a75a5] font-medium">
              Cumulative exposure across top 3 buyers
            </div>
          </div>
        </div>

        {/* Right: Pie Distribution Chart */}
        <div className="lg:col-span-8 neu-raised p-6 rounded-2xl border border-[#d6d0e4]">
          <div className="pb-3 mb-2 border-b border-[#dcd4f2]">
            <h3 className="text-base font-bold text-[#212534]">
              Revenue Contribution Breakdown
            </h3>
            <p className="text-xs text-[#565d70]">
              Proportion of annual turnover generated by each active client account
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-12 gap-6 items-center pt-2">
            <div className="md:col-span-6 h-56 w-full">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={pieData}
                    cx="50%"
                    cy="50%"
                    innerRadius={52}
                    outerRadius={80}
                    paddingAngle={3}
                    dataKey="value"
                  >
                    {pieData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip
                    formatter={(val: any) => [`₹${(Number(val) / 100000).toFixed(2)}L`, 'Annual Revenue']}
                    contentStyle={{
                      backgroundColor: '#ede9f7',
                      border: '1px solid #dcd4f2',
                      borderRadius: '12px',
                      boxShadow: '6px 6px 14px #d2cbe2, -6px -6px 14px #ffffff',
                      fontSize: '12px',
                      color: '#212534',
                    }}
                  />
                </PieChart>
              </ResponsiveContainer>
            </div>

            <div className="md:col-span-6 space-y-2">
              {safeCustomers.map((c, idx) => (
                <div
                  key={c.id}
                  className="flex items-center justify-between p-2.5 rounded-xl bg-white/60 border border-[#dcd4f2] text-xs transition-all hover:bg-white/90"
                >
                  <div className="flex items-center gap-2 truncate">
                    <span
                      className="w-2.5 h-2.5 rounded-full shrink-0"
                      style={{ backgroundColor: COLORS[idx % COLORS.length] }}
                    />
                    <span className="font-bold text-[#212534] truncate">{c.name}</span>
                  </div>
                  <div className="flex items-center gap-2 shrink-0">
                    <span className="font-extrabold text-[#483a7a]">{c.revenueShare}%</span>
                    <span className="text-[#565d70] text-[11px]">
                      (₹{(c.totalRevenue / 100000).toFixed(1)}L)
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Customer Risk Ledger Table */}
      <div className="neu-raised rounded-2xl border border-[#d6d0e4] overflow-hidden">
        <div className="p-4 sm:p-5 border-b border-[#dcd4f2]">
          <h3 className="text-base font-bold text-[#212534]">
            Customer Counterparty Ledger
          </h3>
          <p className="text-xs text-[#565d70]">
            Historical payment track record, outstanding receivables, and instant crisis stress-test actions
          </p>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs text-[#212534]">
            <thead className="bg-[#ede9f7]/70 text-[#483a7a] uppercase tracking-wider font-bold border-b border-[#dcd4f2]">
              <tr>
                <th className="px-4 py-3">Customer Account</th>
                <th className="px-4 py-3">Share %</th>
                <th className="px-4 py-3 text-right">Outstanding Due</th>
                <th className="px-4 py-3">Agreed Terms</th>
                <th className="px-4 py-3">Avg Payment Delay</th>
                <th className="px-4 py-3">Risk Assessment</th>
                <th className="px-4 py-3 text-center">Stress Test</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#dcd4f2]/70">
              {safeCustomers.map((c) => {
                const isHighRisk = c.riskLevel === 'HIGH' || c.riskLevel === 'CRITICAL';
                const isMediumRisk = c.riskLevel === 'MEDIUM';
                const delayDays = c.averagePaymentDelayDays ?? c.averagePaymentDelay ?? 0;

                return (
                  <tr key={c.id} className="hover:bg-white/40 transition-colors">
                    <td className="px-4 py-3 font-bold text-[#212534] flex items-center gap-2">
                      <Building2 className="w-4 h-4 text-[#7a6ab4] shrink-0" />
                      <span>{c.name}</span>
                    </td>
                    <td className="px-4 py-3 font-extrabold text-[#483a7a]">{c.revenueShare}%</td>
                    <td className="px-4 py-3 text-right font-bold text-[#212534]">
                      ₹{c.outstandingAmount.toLocaleString()}
                    </td>
                    <td className="px-4 py-3 text-[#565d70]">{c.creditTermsDays} Days</td>
                    <td className="px-4 py-3">
                      <span
                        className={`font-bold ${
                          delayDays > 10
                            ? 'text-[#b95d77]'
                            : delayDays > 0
                            ? 'text-[#b37346]'
                            : 'text-[#3f7b58]'
                        }`}
                      >
                        +{c.averagePaymentDelayDays} days
                      </span>
                    </td>
                    <td className="px-4 py-3">
                      <span
                        className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                          isHighRisk
                            ? 'bg-[#f8eaef] text-[#733045] border border-[#edd4dc]'
                            : isMediumRisk
                            ? 'bg-[#faefe6] text-[#6b4226] border border-[#f0dcd0]'
                            : 'bg-[#e7f2ec] text-[#235237] border border-[#cfe3d6]'
                        }`}
                      >
                        {c.riskLevel}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-center">
                      <button
                        onClick={() => onSimulateCustomerDelay(c, 15)}
                        className="px-3 py-1 rounded-xl neu-btn text-xs font-bold text-[#483a7a] hover:text-[#212534] flex items-center gap-1 mx-auto bg-white/60"
                      >
                        <SlidersHorizontal className="w-3 h-3 text-[#7a6ab4]" />
                        <span>Simulate 15d Delay</span>
                      </button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
